services:
  # 写服务 - 开发环境
  write-service-dev:
    build:
      context: .
      dockerfile: packages/server/micro-service-write/Dockerfile
      target: builder
    platform: linux/amd64
    container_name: micro-service-write-dev
    ports:
      - '${WRITE_SERVICE_PORT:-3001}:3001'
    environment:
      - NODE_ENV=development
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-localhost}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
    volumes:
      - ./packages/server:/app/packages/server
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/packages/server/node_modules
      - /app/packages/shared/node_modules
    command: ['sh', '-c', 'cd packages/server && pnpm run dev:write-server']
    restart: unless-stopped
    networks:
      - app-network

  # 读服务 - 开发环境
  read-service-dev:
    build:
      context: .
      dockerfile: packages/server/micro-service-read/Dockerfile
      target: builder
    platform: linux/amd64
    container_name: micro-service-read-dev
    ports:
      - '${READ_SERVICE_PORT:-3000}:3000'
    environment:
      - NODE_ENV=development
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-localhost}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
    volumes:
      - ./packages/server:/app/packages/server
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/packages/server/node_modules
      - /app/packages/shared/node_modules
    command: ['sh', '-c', 'cd packages/server && pnpm run dev:read-server']
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
