version: '3.8'

services:
  # 写服务
  write-service:
    build:
      context: ./micro-service-write
    container_name: micro-service-write
    ports:
      - '${WRITE_SERVICE_PORT:-3000}:3000'
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-localhost}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
    volumes:
      - ./micro-service-write:/app
      - /app/node_modules
    networks:
      - app-network

  # 读服务
  read-service:
    build:
      context: ./micro-service-read
    container_name: micro-service-read
    ports:
      - '${READ_SERVICE_PORT:-3001}:3001'
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-localhost}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
    volumes:
      - ./micro-service-read:/app
      - /app/node_modules
    networks:
      - app-network

# 网络配置
networks:
  app-network:
    # 使用Docker的bridge网络驱动
    driver: bridge
